// <auto-generated />
using System;
using CinemaExpress.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaExpress.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Año")
                        .IsRequired();

                    b.Property<string>("Calidad")
                        .IsRequired();

                    b.Property<string>("Géneros")
                        .IsRequired();

                    b.Property<string>("Idioma")
                        .IsRequired();

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<bool>("IsAvailabe");

                    b.Property<DateTime?>("LastSale");

                    b.Property<decimal>("Precio");

                    b.Property<string>("Reparto")
                        .IsRequired();

                    b.Property<string>("Sinópsis")
                        .IsRequired();

                    b.Property<string>("TrailerUrl")
                        .IsRequired();

                    b.Property<string>("Título")
                        .IsRequired();

                    b.Property<string>("TítuloOriginal")
                        .IsRequired();

                    b.Property<string>("VideoUrl")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
